version: '3'

networks:
  net:

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb:1.0
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - net
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress/
    image: wordpress:1.0
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - net
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx:1.0
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 443:443
    networks:
      - net
    depends_on:
      - wordpress

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mous/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mous/data/mysql
